name: tivvit.cz

collections:
  projects:
  talks:

incremental: true

markdown: kramdown

exclude:
  - docker-compose.yaml
  - firebase.json
  - README.md
  - firebase
  - deploy.sh

sass:
  style: compressed

#plugins: TODO 3.5
gem:
  - jekyll-sitemap