name: tivvit.cz
url: https://tivvit.cz

collections:
  projects:
  talks:

incremental: true

markdown: kramdown

exclude:
  - docker-compose.yaml
  - firebase.json
  - README.md
  - firebase
  - deploy.sh

sass:
  style: compressed

gems:
  - jekyll-sitemap