name: tivvit.cz
description: "Vít Listík's personal website containing portfolio projects, machine learning research, talks, and contact information."
author: "Vít Listík"
url: https://tivvit.cz

collections:
  - projects
  - talks

#incremental: true

markdown: kramdown

exclude:
  - docker-compose.yaml
  - firebase.json
  - README.md
  - firebase
  - deploy.sh

sass:
  style: compressed

plugins:
  - jekyll-sitemap