version: '3'
services:
  serve:
    image: jekyll/jekyll:3.4
    ports:
    - "4000:4000"
    volumes:
    - "$PWD:/srv/jekyll"
    command: "jekyll serve --watch"
  generate:
    image: jekyll/jekyll:3.4
    volumes:
    - "$PWD:/srv/jekyll"
    command: "jekyll b"
  firebase-deploy:
    build: firebase
    volumes:
    - ~/.config/:/home/node/.config/
    - $PWD:/app
    command: "firebase deploy"
  firebase-login:
    build: firebase
    volumes:
    - ~/.config/:/home/node/.config/
    command: "firebase login --no-localhost"
  pdf-cv:
    image: openlabs/docker-wkhtmltopdf
    volumes:
    - $PWD:/data
    command: "--print-media-type file:///data/_site/cv.html /data/_site/cv.pdf"
