name: Publish site
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build-publish:

    runs-on: ubuntu-latest
    environment: github-pages

    steps:
    - uses: actions/checkout@v5
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:4.2.2 /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
    - name: build PDF CV
      run: |
        docker run \
        -v ${{ github.workspace }}:/data \
        surnet/alpine-wkhtmltopdf:3.20.2-0.12.6-full --enable-local-file-access --print-media-type file:///data/_site/cv.html /data/_site/cv.pdf
    - name: Firebase CLI Deployment
      uses: w9jds/firebase-action@v15.22.4
      with:
        args: deploy
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
